
export const config = {
    CENTRIFUGO_URL: process.env.CENTRIFUGO_URL,
    CENTRIFUGO_API_KEY: process.env.CENTRIFUGO_API_KEY,
    CENTRIFUGO_TOKEN_HMAC_SECRET_KEY: process.env.CENTRIFUGO_TOKEN_HMAC_SECRET_KEY,
    CENTRIFUGO_ADMIN_URL: process.env.CENTRIFUGO_ADMIN_URL,
    NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
    NEXTAUTH_URL: process.env.NEXTAUTH_URL,
    JWT_SECRET: process.env.JWT_SECRET,
    REGISTRATION_WEBHOOK_URL: process.env.REGISTRATION_WEBHOOK_URL,
    PASSWORD_RESET_WEBHOOK_URL: process.env.PASSWORD_RESET_WEBHOOK_URL,
}