import type { ReactEmailTemplate } from './types.js';

/**
 * React Email Template Renderer
 * 
 * This module handles rendering React Email templates to HTML.
 * In a real implementation, you would use @react-email/render to convert
 * React components to HTML, but for now we'll provide a placeholder
 * that can be extended with the actual React Email rendering logic.
 */
export class ReactEmailRenderer {
  /**
   * Render a React Email template to HTML
   */
  async renderTemplate(
    template: ReactEmailTemplate,
    variables: Record<string, any>
  ): Promise<{
    html: string;
    text: string;
    subject: string;
  }> {
    try {
      // In a real implementation, you would use @react-email/render here
      // For now, we'll provide a placeholder that can be extended
      
      // Generate subject line
      const subject = typeof template.subject === 'function' 
        ? template.subject(variables)
        : template.subject;

      // For now, return a placeholder HTML structure
      // In production, you would use:
      // const html = await render(template.component({ ...variables }))
      const html = this.generatePlaceholderHTML(template, variables);
      
      // Generate plain text version
      const text = this.generatePlainText(template, variables);

      return { html, text, subject };
    } catch (error) {
      console.error(`❌ Failed to render template ${template.name}:`, error);
      throw new Error(`Template rendering failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  /**
   * Generate placeholder HTML for development/testing
   * In production, this would be replaced with actual React Email rendering
   */
  private generatePlaceholderHTML(
    template: ReactEmailTemplate,
    variables: Record<string, any>
  ): string {
    const subject = typeof template.subject === 'function' 
      ? template.subject(variables)
      : template.subject;

    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${subject}</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
  <div style="background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
    <h1 style="color: #007bff; margin: 0 0 10px 0;">${subject}</h1>
    <p style="margin: 0; color: #6c757d;">
      Template: <strong>${template.name}</strong><br>
      Generated: <strong>${new Date().toISOString()}</strong>
    </p>
  </div>
  
  <div style="background-color: white; padding: 20px; border-radius: 8px; border: 1px solid #dee2e6;">
    <h2>Template Variables:</h2>
    <pre style="background-color: #f8f9fa; padding: 10px; border-radius: 4px; overflow-x: auto;">
${JSON.stringify(variables, null, 2)}
    </pre>
    
    <p style="margin-top: 20px; padding: 15px; background-color: #e7f3ff; border-left: 4px solid #007bff; border-radius: 4px;">
      <strong>Note:</strong> This is a placeholder email template. In production, this would be rendered 
      using the actual React Email component: <code>${template.component.name || 'Unknown Component'}</code>
    </p>
    
    ${template.metadata?.description ? `
    <div style="margin-top: 20px; padding: 15px; background-color: #fff3cd; border-left: 4px solid #ffc107; border-radius: 4px;">
      <strong>Template Description:</strong> ${template.metadata.description}
    </div>
    ` : ''}
  </div>
  
  <div style="text-align: center; margin-top: 30px; padding: 20px; color: #6c757d; font-size: 12px;">
    <p>This email was generated by the Email Consumer system</p>
    <p>Template: ${template.name} | Category: ${template.metadata?.category || 'Uncategorized'}</p>
  </div>
</body>
</html>`;
  }

  /**
   * Generate plain text version of the email
   */
  private generatePlainText(
    template: ReactEmailTemplate,
    variables: Record<string, any>
  ): string {
    const subject = typeof template.subject === 'function' 
      ? template.subject(variables)
      : template.subject;

    return `
${subject}

Template: ${template.name}
Generated: ${new Date().toISOString()}

Template Variables:
${Object.entries(variables).map(([key, value]) => `${key}: ${value}`).join('\n')}

${template.metadata?.description ? `\nTemplate Description: ${template.metadata.description}` : ''}

---
This email was generated by the Email Consumer system
Template: ${template.name} | Category: ${template.metadata?.category || 'Uncategorized'}
`.trim();
  }

  /**
   * Validate that a template has all required variables
   */
  validateTemplateVariables(
    template: ReactEmailTemplate,
    variables: Record<string, any>
  ): {
    valid: boolean;
    missing: string[];
    extra: string[];
  } {
    const required = new Set(template.variables);
    const provided = new Set(Object.keys(variables));
    
    const missing = Array.from(required).filter(v => !provided.has(v));
    const extra = Array.from(provided).filter(v => !required.has(v));
    
    return {
      valid: missing.length === 0,
      missing,
      extra,
    };
  }

  /**
   * Get template preview information
   */
  getTemplatePreview(template: ReactEmailTemplate): {
    name: string;
    variables: string[];
    metadata: typeof template.metadata;
    subject: string;
  } {
    return {
      name: template.name,
      variables: template.variables,
      metadata: template.metadata,
      subject: typeof template.subject === 'function' ? '[Dynamic Subject]' : template.subject,
    };
  }
}
