-- Migration: Add auto-incrementing base32 case numbers
-- This migration adds a new caseNumberSeq field and generates base32 case numbers
-- using Crockford Base32 encoding with Feistel permutation for better distribution

-- ==========================================
-- ADD NEW FIELD
-- ==========================================

-- Add the new sequence number field
ALTER TABLE "SupportCase" ADD COLUMN "caseNumberSeq" BIGSERIAL;

-- Make caseNumber nullable (it will be auto-generated by trigger)
ALTER TABLE "SupportCase" ALTER COLUMN "caseNumber" DROP NOT NULL;

-- Add unique constraint on the sequence
ALTER TABLE "SupportCase" ADD CONSTRAINT "SupportCase_caseNumberSeq_unique" UNIQUE ("caseNumberSeq");

-- ==========================================
-- CREATE IMPROVED BASE32 ENCODING FUNCTIONS
-- ==========================================

-- Create the encode_base32 function using Crockford Base32 (no I/L/O/U)
CREATE OR REPLACE FUNCTION encode_base32(num BIGINT)
RETURNS TEXT AS $$
DECLARE
    ALPH TEXT := '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
    result TEXT := '';
    n BIGINT;
    remainder INTEGER;
BEGIN
    n := num;
    
    -- Handle 0 case
    IF n = 0 THEN
        RETURN '0';
    END IF;
    
    -- Convert to base32
    WHILE n > 0 LOOP
        remainder := (n % 32)::INTEGER;
        result := substring(ALPH FROM remainder + 1 FOR 1) || result;
        n := n / 32;
    END LOOP;
    
    RETURN result;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- Create the Feistel permutation function for better distribution
CREATE OR REPLACE FUNCTION feistel25(x BIGINT, key BIGINT)
RETURNS BIGINT AS $$
DECLARE
    MASK25 BIGINT := (1 << 25) - 1;
    L BIGINT;
    R BIGINT;
    newL BIGINT;
    newR BIGINT;
    f BIGINT;
    k1 BIGINT;
    k2 BIGINT;
    k3 BIGINT;
    packed BIGINT;
    i INTEGER;
BEGIN
    x := x & MASK25;
    L := x >> 13;          -- 12 bits
    R := x & ((1 << 13) - 1); -- 13 bits
    
    k1 := key;
    k2 := ((key * 40599) # 2779094181) & ((1 << 32) - 1);
    k3 := ((key * 34283) # 3284376515) & ((1 << 32) - 1);
    
    -- 3 rounds of Feistel network
    FOR i IN 0..2 LOOP
        -- Round function (simplified for PostgreSQL)
        f := ((R # CASE i 
            WHEN 0 THEN k1
            WHEN 1 THEN k2
            WHEN 2 THEN k3
        END) + 2654435769) & ((1 << 32) - 1);
        f := (f # (f >> 16)) & ((1 << 32) - 1);
        f := (f * 2246822507) & ((1 << 32) - 1);
        f := (f # (f >> 13)) & ((1 << 32) - 1);
        f := (f * 3266489917) & ((1 << 32) - 1);
        f := (f # (f >> 16)) & ((1 << 32) - 1);
        f := f & ((1 << 13) - 1); -- return ~13 bits
        
        newL := R;
        newR := (L # f) & ((1 << 12) - 1); -- keep to 12 bits
        L := newL & ((1 << 13) - 1);
        R := newR & ((1 << 12) - 1);
        
        -- Re-pack to 25 bits in consistent way (except last round)
        IF i != 2 THEN
            packed := ((L << 12) | R) & MASK25;
            L := packed >> 13;
            R := packed & ((1 << 13) - 1);
        END IF;
    END LOOP;
    
    RETURN ((L << 12) | R) & MASK25;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- Create the improved case number generation function
CREATE OR REPLACE FUNCTION generate_case_number_base32()
RETURNS TEXT AS $$
DECLARE
    next_seq BIGINT;
    feistel_result BIGINT;
    base32_result TEXT;
BEGIN
    -- Get the next sequence number
    next_seq := nextval('"SupportCase_caseNumberSeq_seq"');
    
    -- Apply Feistel permutation for better distribution
    feistel_result := feistel25(next_seq, 305419896); -- Fixed key for consistency
    
    -- Convert to base32
    base32_result := encode_base32(feistel_result);
    
    -- Pad to 6 characters for better capacity and consistent length
    RETURN lpad(base32_result, 6, '0');
END;
$$ LANGUAGE plpgsql VOLATILE;

-- Create the trigger function
CREATE OR REPLACE FUNCTION trigger_generate_case_number_base32()
RETURNS TRIGGER AS $$
BEGIN
    -- Only generate if caseNumber is not set
    IF NEW."caseNumber" IS NULL OR NEW."caseNumber" = '' THEN
        NEW."caseNumber" := generate_case_number_base32();
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ==========================================
-- REMOVE OLD SYSTEM
-- ==========================================

-- Drop old trigger if it exists
DROP TRIGGER IF EXISTS "TRG_SupportCase_generate_number" ON "SupportCase";

-- Drop old functions if they exist
DROP FUNCTION IF EXISTS generate_case_number() CASCADE;
DROP FUNCTION IF EXISTS trigger_generate_case_number() CASCADE;

-- ==========================================
-- CREATE NEW TRIGGER
-- ==========================================

-- Create the new trigger
CREATE TRIGGER "TRG_SupportCase_generate_number_base32"
    BEFORE INSERT ON "SupportCase"
    FOR EACH ROW
    EXECUTE FUNCTION trigger_generate_case_number_base32();

-- ==========================================
-- UPDATE EXISTING RECORDS
-- ==========================================

-- First, clear existing caseNumber values to allow regeneration
UPDATE "SupportCase" SET "caseNumber" = NULL;

-- Now regenerate all case numbers using the new system
UPDATE "SupportCase" SET "caseNumber" = generate_case_number_base32() WHERE "caseNumberSeq" IS NOT NULL;

-- ==========================================
-- SET SEQUENCE VALUES
-- ==========================================

-- Set the sequence to start at 1 million for future cases
SELECT setval('"SupportCase_caseNumberSeq_seq"', 1000000, false);

-- Ensure the sequence is correctly set after updating existing records
SELECT setval('"SupportCase_caseNumberSeq_seq"', COALESCE((SELECT MAX("caseNumberSeq") FROM "SupportCase"), 1000000), true);

-- ==========================================
-- VERIFICATION
-- ==========================================

-- Show the results
SELECT 
    "caseNumberSeq",
    "caseNumber",
    id,
    "createdAt"
FROM "SupportCase" 
ORDER BY "caseNumberSeq" 
LIMIT 10;
